apiVersion: v1
kind: Service
metadata:
  name: influxdb-influxdb-nodeport
  namespace: default
spec:
  type: NodePort 
  ports:
  - port: 8086
    targetPort: 8086
    name: influxdb
  selector:
    app: influxdb