---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  labels:
    app: influxdb
  name: influxdb-influxdb2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi